---
game:
  background_color: darkgray
  border_color: lightgray
  live_color: yellow
  fps: 60
  resolution:
    - 1600
    - 900
  scale: 20
  timestep: 300 # 1s
  theme: resources/theme_3.json
  image: resources/assets/images/John_H_Conway_2005.jpg